version: '3.1'

services:
  database:
    image: bitnami/postgresql
    restart: always
    environment:
      POSTGRESQL_DATABASE: ead-course
      POSTGRESQL_PASSWORD: admincourse
    ports:
      - 5431:5431
