server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/ead-course
    username: postgres
    password: admincourse
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
      properties:
        hibernate:
          show_slq: true